const todos = [{
    title: 'Order cat food',
    completed: false
}, {
    title: 'Clean kitchen',
    completed: false
}, {
    title: 'Buy food',
    completed: true
}, {
    title: 'Do work',
    completed: false
}, {
    title: 'Exercise',
    completed: true
}]

//create a function to remove a todo using findIndex
let removeTodo = function (todos, text) {
    //...find the item based on text, then remove it
    const index = todos.findIndex(function (todo, index) {
        return todo.title.toLowerCase() === text.toLowerCase()
    })

    if (index > -1) {
        todos.splice(index, 1)
    }
}

// console.log(todos)
// removeTodo(todos, 'do work')
// console.log(todos)

/***********************************************************/

const notes = [{
    title: 'My next trip',
    body: 'I would like to go to Spain'
},{
    title: 'Habits to work on',
    body: 'Exercise. Eating a bit better.'
},{
    title: 'Office modifications',
    body: 'Get a new seat'
}]

//using FILTER. It takes a function as an argument. Creates a new array
//based on our search criteria returning true

const filteredNotes = notes.filter(function (note, index) {
    //we need to return true, for the item to be kept by filter
        //It then gets added to the new array that is generated by filter
    //e.g if i just put return true here, then all notes get added to new array
    //similarly if i just put return false here, none of the notes will be added to new array
    const isTitleMatch = note.title.toLowerCase().includes('ea') 
    const isBodyMatch = note.body.toLowerCase().includes('ea')
    return isTitleMatch || isBodyMatch //return true if either includes what we are looking for
})
//Note: FILTER doesn't change the original array, it just returns a new array
//so we can set it equal to a new variable which is our new array i.e filteredNotes above
console.log(filteredNotes)



/********************************/

//we can wrap the above into a function

const findNotes = function (notes, searchText) {
    const filteredNotes = notes.filter(function (note, index) {
        //need to return true for note to be kept in new array
        const isTitleMatch = note.title.toLowerCase().includes(searchText)
        const isBodyMatch = note.body.toLowerCase().includes(searchText)

    return isTitleMatch || isBodyMatch
    })

    return filteredNotes
}

console.log(findNotes(notes, 'trip'))

/********************************/
//challenge: show only todos that are yet to be completed

const getThingsToDo = function (todos) {
    const thingsToDo = todos.filter(function (todo, index) {
        return todo.completed === false
        //return !todo.completed - this is an alternative way
    })

    return thingsToDo
}
console.log(getThingsToDo(todos))